### ISSUE TITLE
Handle groups better

### ISSUE THREAD

**Issue by plttn** [onedr0p/telegram-couchpotato-bot#18]
As it currently stands right now both the couchpotato and sonarr bots don't handle being in a group very well. 

if I do `@.couchbot /q movie` in a group, I get two messages sent personally back to me, one throwing an error, and one letting me select a movie. Ideally that would be in the group chat itself, not back to a personal thread.

**Comment by onedr0p** [comment]
I initially wrote them to support groups, but I didn't like how other people in the group could see the messages responses from the bot, and their interactions too. I removed the feature because I thought it would raise privacy concerns when you have quite a few people using it. Maybe there is a way, but I am unsure.

One giant leap is to converge the bots together into a single bot, I am not sure when I can get around to it. The Couchpotato bot needs to be updated first to reflect the changes of the Sonarr one. Once I get that out of the way I'll be able to easily (hopefully) just have one bot handle both services (and maybe more).

Thanks for your feedback, and i'll keep this issue open because if there is anyway to use the bots in a group chat while still retaining privacy of the other people using it I would gladly add it when I get the time.

**Comment by plttn** [comment]
FWIW, it seems like with the way it's been implemented with passwords required, a user could auth personally and then use the group chat to request things. This still runs into the issue of the users seeing what other people are requesting. My usecase for this however is that all users are seeing the same content availability anyways, so i don't feel like there is a privacy issue in allowing them to see what others are requesting.  

I've already started digging through the source, and am already in the process of (re)writing it to handle a group. Since you've already gone back on that behavior, I feel like it's not something that needs a pull request, but if you'd be open to the feature being readded, I'll consider making it a pull.

**Comment by plttn** [comment]
And in the time it took me to write that comment, I managed to revert it back to being group-aware (almost, it still handles being mentioned weirdly). 

I do see how there would be an issue with having both bots listen to the /q command when in a group, but i'm not sure what the UX solve would be for that.

**Comment by jayrox** [comment]
in my outdated merged version i changed /q to /tv and /movie
